changed Confirmation of relevance
ImshaBy/imshaby-api pull request #74
Opened 2024-02-26 09:45 UTC by VladSheresh

2024-02-28 16:35 UTC, ViacheslavVV commented on src/main/java/by/imsha/domain/dto/MassInfo.java
> -    public boolean isNeedUpdate() {
его нужно сделать deprecated и вычислять на основании parish

т.е. ещё в MassParishInfo добавить новое поле + заменить поле needUpdate на геттер, вычисляемый на основании 2 полей

2024-02-28 16:38 UTC, ViacheslavVV requested changes

2024-02-28 16:38 UTC, ViacheslavVV commented on src/main/java/by/imsha/rest/MassController.java
>      @PutMapping(params = "parishId")
как по мне, то это операция и метод должен быть POST и раз это операция, то можно /{parishId}/confirm-relevance

но тут уже как у кого опыт, мб Андрей подскажет итоговые наименования

2024-03-12 17:24 UTC, ViacheslavVV commented on src/main/java/by/imsha/domain/dto/MassParishInfo.java
>      @JsonIgnore
для самостоятельного подсчета фронту необходимы будут эти значения, сними с них jsonIgnore (updatePeriodInDays и lastConfirmRelevance), это не меняет совместимости, а фронт сможет переписать логику, чтобы использовать эти 2 значения вместо флага needUpdate

2024-03-12 17:26 UTC, ViacheslavVV commented on src/main/java/by/imsha/domain/Parish.java
> +        return ServiceUtils.needUpdateFromNow(lastConfirmRelevance, getUpdatePeriodInDays());
это nullable поле, пока что его функцию выполняет lastModifiedDate, значит чтобы не сломать логику всем парафиям, нужно обернуть временно в optional и в случае отсутствия использовать lastModifiedDate (так все разом не станут "неактуальными")

optional.ofNullable(lastConfirmRelevance).orElse(lastModifiedDate)

2024-03-13 10:55 UTC, ViacheslavVV approved these changes

2024-03-13 11:12 UTC, childRon approved these changes

2024-03-21 15:49 UTC, merged