added controller for cors
ImshaBy/imshaby-api pull request #76
Opened 2024-05-07 09:39 UTC by VladSheresh

2024-05-08 09:51 UTC, ViacheslavVV requested changes

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/rest/CorsController.java
> +    public ResponseEntity<UpdateEntityInfo> updateCity(final @PathVariable("id") String id, final @RequestBody CorsInfo corsInfo) {
"city"

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/rest/CorsController.java
> +    public ResponseEntity<UpdateEntityInfo> deleteCity(final @PathVariable("id") String id) {
"city"

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/service/CorsConfigService.java
> +    public Cors updateCors(Cors cors) {
при обновлении как и при создании необходима валидация

2024-05-08 09:51 UTC, ViacheslavVV commented on src/test/java/by/imsha/rest/CorsControllerTest.java
> +    void whenCreateRequestHasNoOrigin_then400_andCITY001(final String requestBody) throws Exception {
"city"

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/domain/dto/CorsInfo.java
> +public class CorsInfo {
попробуй `@Value` вместо data , но в новой всё равно record будем использовать, так что не обязательно

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/rest/CorsController.java
> +    @ResponseStatus(HttpStatus.CREATED)
`@ResponseStatus` - что-то избыточное

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/rest/CorsController.java
> +            final HttpServletRequest request) {
`request` не нужен тут

2024-05-08 09:51 UTC, ViacheslavVV commented on src/main/java/by/imsha/service/CorsConfigService.java
> +    public Cors createCors(final @Valid Cors cors) {
это и так сервис cors, можно убрать из названий методов постфикс *Cors

2024-06-15 04:56 UTC, childRon approved these changes

2024-06-15 05:04 UTC, childRon commented on src/main/java/by/imsha/service/CorsConfigService.java
> +    public Cors createCors(final @Valid Cors cors) {
@VladSheresh  @ViacheslavVV - надо еще доделать ПР? или могу мержить?

2024-06-15 09:44 UTC, ViacheslavVV commented on src/main/java/by/imsha/service/CorsConfigService.java
> +    public Cors createCors(final @Valid Cors cors) {
@VladSheresh ещё не все комменты вроде поправил, но думаю там осталась только косметика, так что можно сливать @childRon

2024-06-25 09:53 UTC, ViacheslavVV approved these changes

2024-07-10 06:51 UTC, merged