added search for users from fusionAuth
ImshaBy/imshaby-api pull request #82
Opened 2024-12-09 13:41 UTC by VladSheresh

2024-12-09 13:54 UTC, childRon commented
Влад, есть такой момент : в некоторых парафиях больше одногл волонтёра, потому что я иль Витя их добавили в список себе (чтоб иметь доступ к парафіямі и прочее). Надо исключить нас из подсчёта. Позже обсудим как сделать. Первые мысли : добавить атрибут пользователю в fusionauth

2024-12-09 20:49 UTC, ViacheslavVV requested changes

2024-12-09 20:49 UTC, ViacheslavVV commented on common/src/main/java/by/imsha/feign/dto/request/UserSearchFilterRequest.java
> +    public static class searchFilter {
- [ ] searchFilter -> SearchFilter

2024-12-09 20:49 UTC, ViacheslavVV commented on common/src/main/java/by/imsha/service/VolunteerService.java
> +                    .flatMap(u -> Optional.ofNullable(u.getData().getParishes()).stream())
- [ ] добавь ещё безопасных переходов  ofNullable(u).map(User::getData).map(Data::getParishes).stream()

и где-то между map методами нужно будет вставить фильтрацию по пользователям, которые волонтёрят в чужих парафиях

2024-12-09 20:49 UTC, ViacheslavVV commented on common/src/main/java/by/imsha/service/VolunteerService.java
> +        while (true) {
- [ ] можно было do while (без бесконечного цикла)

2024-12-09 20:57 UTC, ViacheslavVV commented on server/src/main/resources/application.yml
> +fusionAuth:
добавь ещё 1 поле и бери из него пользователей, парафии которых не нужно учитывать

`
fusionAuth:
  ignore-users: 
    - andrei.misan@gmail.com
    - victar.misan@gmail.com
`

2024-12-10 16:52 UTC, NikDark approved these changes

2024-12-10 16:53 UTC, merged